abstract class English {
  static const Map<String, String> values = {
    //Error messages
    'error_view_scale':
        'Mobile View & Tablet View are not supported yet. Please use a desktop or laptop to view this page.',
    'email_is_required': 'Email is required',
    'invalid_email': 'Invalid email',
    'invalid_confirm_password': 'Invalid confirm password',
    'confirm_password_is_required': 'Confirm password is required',
    'passwords_do_not_match': 'Passwords do not match',
    'password_is_required': 'Password is required',
    'password_must_be_at_least_6_characters':
        'Password must be at least 6 characters',

    'error_from_supabase': 'Supabase error',
    'error_table': 'Table error',
    'table_already_exists': 'Table already exists',
    'delete_table': 'Delete table',
    'edit_table': 'Edit table',
    'empty_table_name_error': 'Table name is empty',
    'table_name_already_exists': 'Table name already exists',
    'table_length_error': 'Table name length must be less than 20 characters',
    'empty_project_name_error': 'Project name is empty',
    'project_name_already_exists': 'Project name already exists',
    'project_length_error':
        'Project name length must be less than 20 characters',
    'table_short_error': 'Table name length must be more than 3 characters',
    'project_short_error': 'Project name length must be more than 3 characters',
    'project_is_exist': 'Project already exists',
    'empty_task_name_error': 'Task name is empty',
    'task_name_already_exists': 'Task name already exists',
    'task_length_error': 'Task name length must be less than 20 characters',
    'task_short_error': 'Task name length must be more than 3 characters',
    'invalid_date': 'Invalid date',
    'invalid_time': 'Invalid time',
    'invalid_start_date': 'Invalid start date',
    'invalid_end_date': 'Invalid end date',
    'invalid_start_time': 'Invalid start time',
    'invalid_end_time': 'Invalid end time',
    //Warning messages

    //Info messages
    'lang': 'Ukrainian',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'login': 'Login',
    'register': 'Register',
    'sign_out': 'Sign out',
    'welcome_back': 'Welcome',
    'login_with_social_media': 'Login with social media:',
    'have_account': 'Already have an account?',
    'have_not_account': 'Don\'t have an account?',
    'success': 'Success',
    'checkEmailForConfirmation': 'Check your email for confirmation',
    'ok': 'OK',
    'create_project': 'Create Project',
    'create_new_project': 'Create New Project',
    'project_name': 'Project Name',
    'cancel': 'Cancel',
    'no_project': 'No project',
    'project': 'Project',
    'cretae_table': 'Create Table',
    'table_name': 'Table Name',
    'no_table': 'No table',
    'edit_project': 'Edit Project',
    'create_task': 'Create Task',
    'task_name': 'Task Name',
    'no_task': 'No task',
    'edit_task': 'Edit Task',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'start_time': 'Start Time',
    'end_time': 'End Time',
    'tag': 'Tag',
    'assigned_user': 'Assigned User',
    'description': 'Description',
    'comments': 'Comments',
    'files': 'Files',
    'loading': 'Loading',
    'something_went_wrong':
        'Ops... Something went wrong! Please, check your internet connection and try to reload website.',
    'uploaded_files': 'Uploaded files',
  };
}
